In [54]:
import tensorflow
import keras 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import layers

In [55]:
data = {
    'study_hours': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'sleep_hours': [8, 7.5, 7, 6.5, 6, 5.5, 5, 4.5, 4, 3.5],
    'pass_exam': [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)
df

   study_hours  sleep_hours  pass_exam
0            1          8.0          0
1            2          7.5          0
2            3          7.0          0
3            4          6.5          0
4            5          6.0          1
5            6          5.5          1
6            7          5.0          1
7            8          4.5          1
8            9          4.0          1
9           10          3.5          1

In [56]:
df.columns

Index(['study_hours', 'sleep_hours', 'pass_exam'], dtype='object')

In [57]:
X = df[['study_hours', 'sleep_hours']]
y = df['pass_exam']

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, train_size=0.8)
X_train

   study_hours  sleep_hours
5            6          5.5
0            1          8.0
7            8          4.5
2            3          7.0
9           10          3.5
4            5          6.0
3            4          6.5
6            7          5.0

In [68]:
print(X_train.shape)
print(X_test.shape)

(8, 2)
(2, 2)

In [67]:
normaliser = MinMaxScaler()
X_train_scaled = normaliser.fit_transform(X_train)
X_test_scaled = normaliser.transform(X_test)

print(X_train_scaled.shape)
print(X_test_scaled.shape)

(8, 2)
(2, 2)

In [72]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [74]:
history = model.fit(X_train.values, y_train.values,
                    validation_data=(X_test.values, y_test.values),
                    epochs=100, batch_size=4, verbose=0)

In [75]:
history